### ISSUE TITLE
Got : AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by andrimirandi** [danieliu/play-scraper#14]
Got this error after installing play_scraper and try to import it
please help,

thanks
```
[root@CT114 ~]# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import play_scraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/play_scraper/__init__.py", line 13, in <module>
    from play_scraper.api import (
  File "/usr/lib/python2.7/site-packages/play_scraper/api.py", line 11, in <module>
    from play_scraper import scraper
  File "/usr/lib/python2.7/site-packages/play_scraper/scraper.py", line 15, in <module>
    from bs4 import BeautifulSoup, SoupStrainer
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**Comment by andrimirandi** [comment]
Hello, after a view poke around I found the solution... basically its because of incompatible library updates
when I run
```
pip install --upgrade beautifulsoup4
pip install --upgrade html5lib
pip install --upgrade requests==2.1.0
```
everything work as expected
