### ISSUE TITLE
Outdated GPlay class name + uncaught exception

### ISSUE THREAD

**Issue by rajcanius** [danieliu/play-scraper#38]
**Describe the bug**
Scraper crashes due to outdated class name. This issue causes an Exception to be raised later in the parsing process. This exception is not caught and crashes the scraper.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/play_scraper/api.py", line 22, in details
    return s.details(app_id)
  File "site-packages/play_scraper/scraper.py", line 83, in details
    app_json = parse_app_details(soup)
  File "site-packages/play_scraper/utils.py", line 312, in parse_app_details
    soup.select_one('.xyOfqd'))
  File "site-packages/play_scraper/utils.py", line 138, in parse_additional_info
    section_titles_divs = [x for x in soup.select('div.hAyfc div.BgcNfc')]
AttributeError: 'NoneType' object has no attribute 'select'

**To Reproduce**
Request details of any package name.

**Expected behavior**
1. Scraper returns additional_info_data variable in utils.py/parse_app_details(soup) as empty dictionary or
2.scraper makes check if utils.py/parse_additional_info(soup)/soup is not None.
Depends on the author's decision.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.3]
 - Python Version [2.7.10]
 - play_scraper Version [0.5.3]

**Additional context**
While obtaining details about an app today (2019-03-26) I have noticed, that tool starts crashing on utils.py, line 312 (... soup.select_one('.xyOfqd')))

1. After some investigation I have found out, that class name **xyOfqd** is not used by Google Play anymore. Instead class name **IxB2fe** is currently used by Google Play Store.
2. Preventing utils.py/parse_app_details(soup)/additional_info_data to be set as None might help with NoneType object accessing and prevent the AttributeError in utils.py, line 138

**Comment by rajcanius** [comment]
Duplicate with Exception Thrown by play-scraper.details Method #37
My apologies, did not notice the bug report #37
