### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'select'

### ISSUE THREAD

**Issue by Smingvin** [danieliu/play-scraper#39]
I tried running the sample code from the readme:

```
import play_scraper
print(play_scraper.details('com.android.chrome'))
```

I get the following output:

```
Traceback (most recent call last):
  File "bug.py", line 2, in <module>
    print(play_scraper.details('com.android.chrome'))
  File "/usr/local/lib/python3.7/site-packages/play_scraper/api.py", line 22, in details
    return s.details(app_id)
  File "/usr/local/lib/python3.7/site-packages/play_scraper/scraper.py", line 83, in details
    app_json = parse_app_details(soup)
  File "/usr/local/lib/python3.7/site-packages/play_scraper/utils.py", line 312, in parse_app_details
    soup.select_one('.xyOfqd'))
  File "/usr/local/lib/python3.7/site-packages/play_scraper/utils.py", line 138, in parse_additional_info
    section_titles_divs = [x for x in soup.select('div.hAyfc div.BgcNfc')]
AttributeError: 'NoneType' object has no attribute 'select'
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Python Version 3.7.2
 - play_scraper Version 0.5.1

**Comment by kushalkrip** [comment]
I had the same issue. It can be solved by the following steps:
1. Go to "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\play_scraper\utils.py", if on windows.
or locate "utils.py" in "play_scraper".
2. Change the following:
Before:
additional_info_data = parse_additional_info(
soup.select_one('.xyOfqd'))

Now
additional_info_data = parse_additional_info(
soup.select_one('.IxB2fe'))

It works like a charm.
