### ISSUE TITLE
Outdated css class name for GPlay

### ISSUE THREAD

**Issue by Kyry** [danieliu/play-scraper#42]
**Describe the bug**
Google probably made update yesterday causing `detail` method to stop working
play_scraper/utils.py", line 240, in parse_app_details\n    icon = (soup.select_one(\'.dQrBL img.ujDFqe\')\nAttributeError: \'NoneType\' object has no attribute \'attrs\''

**To Reproduce**
Call `detail` method of with any package name

**Desktop (please complete the following information):**
- play-scraper==0.5.4

**Comment by VProgramMist** [comment]
Replace:
`icon = (soup.select_one('.dQrBL img.ujDFqe')`
 with: 
`icon = (soup.select_one ('. XSyT2c img.T75of')`

**Comment by kushalkrip** [comment]
> Replace:
> `icon = (soup.select_one('.dQrBL img.ujDFqe')`
> with:
> `icon = (soup.select_one ('. XSyT2c img.T75of')`

The above correction gives an exception as follows: 
`

Traceback (most recent call last):                                                                                                                                                                                   File "print_the_manifest.py", line 9, in                                                                                                                                                                     print(play_scraper.details('com.android.chrome'))                                                                                                                                                                File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\play_scraper\api.py", line 22, in details                                                                                                 return s.details(app_id)                                                                                                                                                                                         File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\play_scraper\scraper.py", line 83, in details                                                                                             app_json = parse_app_details(soup)                                                                                                                                                                               File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\play_scraper\utils.py", line 240, in parse_app_details                                                                                    icon = (soup.select_one ('. XSyT2c img.T75of')                                                                                                                                                                   File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\element.py", line 1344, in select_one                                                                                                 value = self.select(selector, namespaces, 1, **kwargs)                                                                                                                                                           File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\element.py", line 1376, in select                                                                                                     return soupsieve.select(selector, self, namespaces, limit, **kwargs)                                                                                                                                             File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\__init__.py", line 108, in select                                                                                               return compile(select, namespaces, flags).select(tag, limit)                                                                                                                                                     File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\__init__.py", line 59, in compile                                                                                               return cp._cached_css_compile(pattern, namespaces, flags)                                                                                                                                                        File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\css_parser.py", line 192, in _cached_css_compile                                                                                CSSParser(pattern, flags).process_selectors(),                                                                                                                                                                   File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\css_parser.py", line 894, in process_selectors                                                                                  return self.parse_selectors(self.selector_iter(self.pattern), index, flags)                                                                                                                                      File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\css_parser.py", line 744, in parse_selectors                                                                                    key, m = next(iselector)                                                                                                                                                                                         File "C:\Users\KK\AppData\Local\Programs\Python\Python37\lib\site-packages\soupsieve\css_parser.py", line 881, in selector_iter                                                                                      raise SyntaxError(msg)                                                                                                                                                                                         SyntaxError: Malformed class selector at position 0
--


`

**Comment by kushalkrip** [comment]
> Replace:
> `icon = (soup.select_one('.dQrBL img.ujDFqe')`
> with:
> `icon = (soup.select_one ('. XSyT2c img.T75of')`

The above correction gives an exception as follows: 
![Capture](https://user-images.githubusercontent.com/39152286/57572950-fe044d80-743e-11e9-8237-28d2eebbbefa.JPG)

**Comment by danieliu** [comment]
@kushalkrip please update to the latest v0.5.5
