### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by imedaouidene** [danieliu/play-scraper#9]
`Traceback (most recent call last):
  File "test_desc.py", line 2, in <module>
    print (play_scraper.details('com.z2p.devops.mathpuzzel'))
  File "/home/vmstation/.local/lib/python2.7/site-packages/play_scraper/api.py", line 22, in details
    return s.details(app_id)
  File "/home/vmstation/.local/lib/python2.7/site-packages/play_scraper/scraper.py", line 341, in details
    app_json = self._parse_app_details(soup)
  File "/home/vmstation/.local/lib/python2.7/site-packages/play_scraper/scraper.py", line 254, in _parse_app_details
    soup.select_one('.xyOfqd'))
  File "/home/vmstation/.local/lib/python2.7/site-packages/play_scraper/scraper.py", line 168, in _parse_additional_info
    'developer_address': developer_address.strip()}
AttributeError: 'NoneType' object has no attribute 'strip'
`

**Comment by danieliu** [comment]
Fixed in `0.2.4`
